mode = "dark"
accent = "#a6ed47"
selection = "#45335f"
muted = "#706381"
background = "#14101d"
dark_background = "#100c17"
darker_background = "#0b0910"
lighter_background = "#251b35"
foreground = "#e5dff0"
dark_foreground = "#998cae"
light_foreground = "#cbbfdd"
bright_foreground = "#f5efff"
red = "#f15b6c"
yellow = "#eed878"
orange = "#ff9b54"
green = "#a6ed47"
cyan = "#72d6c5"
blue = "#a38be8"
magenta = "#c18cf5"
brown = "#99765e"
bright_red = "#ff8190"
bright_yellow = "#ffe99c"
bright_green = "#c2ff75"
bright_cyan = "#9aeee0"
bright_blue = "#bba5ff"
bright_magenta = "#dfb0ff"
hyprland_active_border = "rgba(a38be8ff) rgba(a6ed47ff) 45deg"
hyprland_inactive_border = "rgba(45335fcc)"
